name: "nxlvlsoftware/docker-build"
description: "Build docker images & push to a docker registry."
inputs:
  path:
    description: "The path to the Dockerfile's build context."
    default: "."
    required: true
  file:
    description: "Name or path to the Dockerfile to build. Must be in the path dir."
    default: "Dockerfile"
    required: true
  name:
    description: "The docker image name."
    required: true
  tag:
    description: "The docker image tag name."
    required: true
  extra_args:
    description: "Extra arguments to pass to the docker build command."
    default: ""
    required: false
  registry_username:
    description: "The docker registry username for the account to publish the image from."
    required: true
  registry_password:
    description: "The docker registry password for the account to publish the image from."
    required: true
  registry_uri:
    description: "The docker registry uri for the account to publish the image from."
    required: false
  pull:
    description: "Should we pull existing images before the build to speed up the build? Uses the current tag and version if true or the the value should be in image:version format."
    default: "true"
    required: false
  push:
    description: "Should we push the built image to the registry?"
    default: "true"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"